version: "3"
services:
  chat-server:
    container_name: chat-server
    restart: unless-stopped
    image: hussienfahmy/ktor-chat-server
    depends_on:
      - chat-db
    ports:
      - "87:8080"
    environment:
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=chat-db
      - DATABASE_PORT=27017

  chat-db:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - chat-db
    ports:
      - "88:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongo:27017/